<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="petriNet" nsURI="http://www.example.org/ecore" nsPrefix="ecore">
  <eClassifiers xsi:type="ecore:EClass" name="Place">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jeton" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="liens" upperBound="-1"
        eType="#//Arc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="liens" lowerBound="2" upperBound="-1"
        eType="#//Arc"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Arc">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="poid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="place" lowerBound="1" eType="#//Place"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transition" lowerBound="1"
        eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sens" lowerBound="1" eType="#//ArcSens"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadArc" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ArcSens">
    <eLiterals name="placeToTransition"/>
    <eLiterals name="transitionToPlace" value="1"/>
  </eClassifiers>
</ecore:EPackage>
    