/*
 * generated by Xtext 2.28.0
 */
package fr.n7.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractPDL3ScopeProvider extends DelegatingScopeProvider {
}
