/*
 * generated by Xtext 2.28.0
 */
package fr.n7.ui;

import com.google.inject.Injector;
import fr.n7.PDL3.ui.internal.PDL3Activator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class PDL3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(PDL3Activator.class);
	}
	
	@Override
	protected Injector getInjector() {
		PDL3Activator activator = PDL3Activator.getInstance();
		return activator != null ? activator.getInjector(PDL3Activator.FR_N7_PDL3) : null;
	}

}
