/*
 * generated by Xtext 2.28.0
 */
package fr.n7.ui.tests;

import com.google.inject.Injector;
import fr.n7.PDL3.ui.internal.PDL3Activator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class PDL3UiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return PDL3Activator.getInstance().getInjector("fr.n7.PDL3");
	}

}
